INSERT state values ('AL', 'Alabama');
INSERT state values ('AK', 'Alaska');
INSERT state values ('AZ', 'Arizona');
INSERT state values ('AR', 'Arkansas');
INSERT state values ('CA', 'California');
INSERT state values ('CO', 'Colorado');
INSERT state values ('CT', 'Connecticut');
INSERT state values ('DE', 'Delaware');
INSERT state values ('FL', 'Florida');
INSERT state values ('GA', 'Georgia');
INSERT state values ('HI', 'Hawaii');
INSERT state values ('ID', 'Idaho');
INSERT state values ('IL', 'Illinois');
INSERT state values ('IN', 'Indiana');
INSERT state values ('IA', 'Iowa');
INSERT state values ('KS', 'Kansas');
INSERT state values ('KY', 'Kentucky');
INSERT state values ('LA', 'Louisiana');
INSERT state values ('ME', 'Maine');
INSERT state values ('MD', 'Maryland');
INSERT state values ('MA', 'Massachusetts');
INSERT state values ('MI', 'Michigan');
INSERT state values ('MN', 'Minnesota');
INSERT state values ('MS', 'Mississippi');
INSERT state values ('MO', 'Missouri');
INSERT state values ('MT', 'Montana');
INSERT state values ('NE', 'Nebraska');
INSERT state values ('NV', 'Nevada');
INSERT state values ('NH', 'New Hampshire');
INSERT state values ('NJ', 'New Jersey');
INSERT state values ('NM', 'New Mexico');
INSERT state values ('NY', 'New York');
INSERT state values ('NC', 'North Carolina');
INSERT state values ('ND', 'North Dakota');
INSERT state values ('OH', 'Ohio');
INSERT state values ('OK', 'Oklahoma');
INSERT state values ('OR', 'Oregon');
INSERT state values ('PA', 'Pennsylvania');
INSERT state values ('RI', 'Rhode Island');
INSERT state values ('SC', 'South Carolina');
INSERT state values ('SD', 'South Dakota');
INSERT state values ('TN', 'Tennessee');
INSERT state values ('TX', 'Texas');
INSERT state values ('UT', 'Utah');
INSERT state values ('VT', 'Vermont');
INSERT state values ('VA', 'Virginia');
INSERT state values ('WA', 'Washington');
INSERT state values ('WV', 'West Virginia');
INSERT state values ('WI', 'Wisconsin');
INSERT state values ('WY', 'Wyoming');
